"""add_stripe_payout_id_to_payments

Revision ID: 07633e867b50
Revises: f80daf1c4ecb
Create Date: 2026-05-03 17:18:13.385466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07633e867b50'
down_revision: Union[str, None] = 'f80daf1c4ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_payout_id', sa.String(length=255), nullable=True))
    op.alter_column('payments', 'club_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_payments_stripe_payout_id'), 'payments', ['stripe_payout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_stripe_payout_id'), table_name='payments')
    op.alter_column('payments', 'club_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('payments', 'stripe_payout_id')
    # ### end Alembic commands ###
