"""drop_court_blackouts

Revision ID: 1065b10c5c74
Revises: 24a1464d08d9
Create Date: 2026-03-30 19:26:10.658881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1065b10c5c74'
down_revision: Union[str, None] = '24a1464d08d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('court_blackouts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_blackouts',
    sa.Column('court_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], name='court_blackouts_court_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='court_blackouts_pkey')
    )
    # ### end Alembic commands ###
