"""wallet_club_debts

Revision ID: 3a758d32ab8d
Revises: 80803a6bae79
Create Date: 2026-05-12 19:10:40.749612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a758d32ab8d'
down_revision: Union[str, None] = '80803a6bae79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_club_debts',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('wallet_transaction_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stripe_transfer_id', sa.String(length=255), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['wallet_transaction_id'], ['wallet_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_transaction_id')
    )
    op.create_index(op.f('ix_wallet_club_debts_club_id'), 'wallet_club_debts', ['club_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_club_debts_club_id'), table_name='wallet_club_debts')
    op.drop_table('wallet_club_debts')
    # ### end Alembic commands ###
