"""add analytics_refresh_log

Revision ID: 520ea227119a
Revises: a04c76851993
Create Date: 2026-06-01 17:39:57.624557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520ea227119a'
down_revision: Union[str, None] = 'a04c76851993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_refresh_log',
    sa.Column('view_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='refreshstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_refresh_log_view_started', 'analytics_refresh_log', ['view_name', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analytics_refresh_log_view_started', table_name='analytics_refresh_log')
    op.drop_table('analytics_refresh_log')
    # create_table auto-created the enum type; drop it so re-upgrade succeeds.
    op.execute('DROP TYPE IF EXISTS refreshstatus')
    # ### end Alembic commands ###
