"""add_payouts_table

Revision ID: 8443a533d9d9
Revises: dff4cf6de626
Create Date: 2026-06-13 14:55:24.159669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8443a533d9d9'
down_revision: Union[str, None] = 'dff4cf6de626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('stripe_payout_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_connect_account_id', sa.String(length=255), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_transit', 'paid', 'failed', 'canceled', name='payoutstatus'), nullable=False),
    sa.Column('arrival_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statement_descriptor', sa.String(length=255), nullable=True),
    sa.Column('failure_code', sa.String(length=255), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('reconciliation_status', sa.Enum('unmatched', 'matched', 'partial', 'discrepancy', name='payoutreconstatus'), nullable=False),
    sa.Column('matched_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discrepancy_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payout_id')
    )
    op.create_index('ix_payouts_arrival', 'payouts', ['arrival_date'], unique=False)
    op.create_index('ix_payouts_club_recon', 'payouts', ['club_id', 'reconciliation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payouts_club_recon', table_name='payouts')
    op.drop_index('ix_payouts_arrival', table_name='payouts')
    op.drop_table('payouts')
    op.execute('DROP TYPE IF EXISTS payoutreconstatus')
    op.execute('DROP TYPE IF EXISTS payoutstatus')
    # ### end Alembic commands ###
