"""add ix_waitlist_club_date index

Revision ID: 8800a16daf16
Revises: ae37b6ee82be
Create Date: 2026-05-30 14:31:24.257406

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8800a16daf16'
down_revision: Union[str, None] = 'ae37b6ee82be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_waitlist_club_date', 'waitlist_entries', ['club_id', 'desired_date', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waitlist_club_date', table_name='waitlist_entries')
    # ### end Alembic commands ###
