"""court_hold_expiry

Revision ID: 92c0f1557d7e
Revises: fa46b223afc9
Create Date: 2026-05-29 13:05:33.561760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c0f1557d7e'
down_revision: Union[str, None] = 'fa46b223afc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_players', sa.Column('payment_deadline', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_booking_players_deadline', 'booking_players', ['payment_deadline'], unique=False, postgresql_where=sa.text("payment_status = 'pending'"))
    op.add_column('bookings', sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'hold_expires_at')
    op.drop_index('ix_booking_players_deadline', table_name='booking_players', postgresql_where=sa.text("payment_status = 'pending'"))
    op.drop_column('booking_players', 'payment_deadline')
    # ### end Alembic commands ###
