"""payments_add_stripe_destination_payment_id

Revision ID: a3ad99663232
Revises: 0fcac3948b73
Create Date: 2026-05-21 07:14:11.709227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ad99663232'
down_revision: Union[str, None] = '0fcac3948b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_destination_payment_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payments_stripe_destination_payment_id'), 'payments', ['stripe_destination_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_stripe_destination_payment_id'), table_name='payments')
    op.drop_column('payments', 'stripe_destination_payment_id')
    # ### end Alembic commands ###
