"""G7 analytics schema court_utilisation_snapshots users demographics clubs timezone

Revision ID: b210c7b03579
Revises: 8800a16daf16
Create Date: 2026-05-30 14:46:07.168610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b210c7b03579'
down_revision: Union[str, None] = '8800a16daf16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the enum type explicitly first — asyncpg's create_type auto-detection
    # is unreliable, so we never let add_column emit the CREATE TYPE (create_type=False).
    op.execute("CREATE TYPE gender AS ENUM ('male', 'female', 'other', 'prefer_not_to_say')")
    gender_enum = postgresql.ENUM(
        'male', 'female', 'other', 'prefer_not_to_say', name='gender', create_type=False
    )

    op.create_table('court_utilisation_snapshots',
    sa.Column('club_id', sa.UUID(), nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('hour_of_day', sa.SmallInteger(), nullable=True),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('booked_slots', sa.Integer(), nullable=False),
    sa.Column('utilisation_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('revenue_actual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('revenue_potential', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('avg_booking_lead_time_h', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'snapshot_date', 'hour_of_day', name='uq_court_utilisation_court_date_hour')
    )
    op.add_column('clubs', sa.Column('timezone', sa.String(length=50), server_default='Europe/London', nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', gender_enum, nullable=True))
    op.add_column('users', sa.Column('postcode', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'postcode')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('clubs', 'timezone')
    op.drop_table('court_utilisation_snapshots')
    op.execute('DROP TYPE IF EXISTS gender')
    # ### end Alembic commands ###
